# -*- coding: utf-8 -*-
"""CropRecommendation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16h3PYt52CFyuSjppDEXrGyN1gJe29jGh
"""

import pandas as pd

df = pd.read_csv("Crop_recommendation.csv")

df.head()

# Used for loading and handling datasets
import pandas as pd

# Used for numerical operations
import numpy as np

# Used for plotting graphs
import matplotlib.pyplot as plt

# Used for statistical visualizations
import seaborn as sns

# Import dataset
df = pd.read_csv("Crop_recommendation.csv")

df.info()

# Display first 5 rows to verify successful import
df.head()

df.isnull().sum()

# First 5 rows
print("First 5 Rows:")
display(df.head())

# Last 5 rows
print("Last 5 Rows:")
display(df.tail())

# Dataset shape
print("\nDataset Shape (Rows, Columns):")
print(df.shape)

# Dataset information
print("\nDataset Information:")
df.info()

# Statistical summary
print("\nStatistical Summary:")
display(df.describe())

# Missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Duplicate records
print("\nDuplicate Records:")
print(df.duplicated().sum())

# Column names
print("\nColumn Names:")
print(df.columns.tolist())

# Crop distribution
print("\nCrop Distribution:")
display(df['label'].value_counts())

# =========================
# GRAPHICAL REPRESENTATION
# =========================

# Crop Distribution
plt.figure(figsize=(12,6))
sns.countplot(x='label', data=df)
plt.title("Crop Distribution")
plt.xticks(rotation=90)
plt.show()

# Correlation Heatmap
plt.figure(figsize=(8,6))
sns.heatmap(df.drop('label', axis=1).corr(), annot=True, cmap='coolwarm')
plt.title("Feature Correlation Heatmap")
plt.show()

# Feature Distributions
df.drop('label', axis=1).hist(figsize=(12,8))
plt.tight_layout()
plt.show()

# Boxplots for Outlier Detection
for col in df.columns[:-1]:
    plt.figure(figsize=(5,3))
    sns.boxplot(x=df[col])
    plt.title(f"Boxplot of {col}")
    plt.show()

# Separate features and target

X = df.drop('label', axis=1)
y = df['label']

# Split dataset into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Check shapes

print("X_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape :", y_test.shape)

# Feature Scaling

from sklearn.preprocessing import StandardScaler

# Create scaler object
scaler = StandardScaler()

# Fit and transform training data
X_train_scaled = scaler.fit_transform(X_train)

# Transform testing data
X_test_scaled = scaler.transform(X_test)

# Check shapes
print("X_train_scaled shape:", X_train_scaled.shape)
print("X_test_scaled shape :", X_test_scaled.shape)

# Logistic Regression Model

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Create model
lr = LogisticRegression(max_iter=1000)

# Train model
lr.fit(X_train_scaled, y_train)

# Predictions
y_pred_lr = lr.predict(X_test_scaled)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred_lr))

# KNN

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train_scaled, y_train)

y_pred_knn = knn.predict(X_test_scaled)

print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))

# Decision Tree

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))

# Random Forest

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))

# SVM

from sklearn.svm import SVC

svm = SVC()
svm.fit(X_train_scaled, y_train)

y_pred_svm = svm.predict(X_test_scaled)

print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))

# Naive Bayes

from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(X_train_scaled, y_train)

y_pred_nb = nb.predict(X_test_scaled)

print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred_nb))

# Multi-Layer Perceptron (Neural Network)

from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(
    hidden_layer_sizes=(100, 50),
    max_iter=500,
    random_state=42
)

mlp.fit(X_train_scaled, y_train)

y_pred_mlp = mlp.predict(X_test_scaled)

print("MLP Accuracy:", accuracy_score(y_test, y_pred_mlp))

# Display Accuracy of All Models

print("Logistic Regression Accuracy :", accuracy_score(y_test, y_pred_lr))
print("KNN Accuracy                 :", accuracy_score(y_test, y_pred_knn))
print("Decision Tree Accuracy       :", accuracy_score(y_test, y_pred_dt))
print("Random Forest Accuracy       :", accuracy_score(y_test, y_pred_rf))
print("SVM Accuracy                 :", accuracy_score(y_test, y_pred_svm))
print("Naive Bayes Accuracy         :", accuracy_score(y_test, y_pred_nb))
print("MLP Accuracy                 :", accuracy_score(y_test, y_pred_mlp))

# Compare Model Accuracies using Bar Chart

models = [
    "Logistic Regression",
    "KNN",
    "Decision Tree",
    "Random Forest",
    "SVM",
    "Naive Bayes",
    "MLP"
]

accuracies = [
    accuracy_score(y_test, y_pred_lr),
    accuracy_score(y_test, y_pred_knn),
    accuracy_score(y_test, y_pred_dt),
    accuracy_score(y_test, y_pred_rf),
    accuracy_score(y_test, y_pred_svm),
    accuracy_score(y_test, y_pred_nb),
    accuracy_score(y_test, y_pred_mlp)
]

plt.figure(figsize=(10, 5))
bars = plt.bar(models, accuracies)

plt.title("Model Accuracy Comparison")
plt.xlabel("Models")
plt.ylabel("Accuracy")
plt.xticks(rotation=45)
plt.ylim(0.9, 1.01)

# Display accuracy values on bars
for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width()/2,
        height,
        f"{height:.4f}",
        ha='center'
    )

plt.show()

# Confusion Matrix for Naive Bayes

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_nb)

plt.figure(figsize=(12, 10))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=nb.classes_,
    yticklabels=nb.classes_
)

plt.title("Confusion Matrix - Naive Bayes")
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.show()

# Count Correct and Incorrect Predictions

correct = (y_test == y_pred_nb).sum()
incorrect = (y_test != y_pred_nb).sum()

# Plot Graph

plt.figure(figsize=(6,4))
sns.barplot(
    x=["Correct Predictions", "Incorrect Predictions"],
    y=[correct, incorrect]
)

plt.title("Naive Bayes Prediction Results")
plt.ylabel("Number of Samples")

for i, value in enumerate([correct, incorrect]):
    plt.text(i, value, str(value), ha='center')

plt.show()

print("Correct Predictions :", correct)
print("Incorrect Predictions :", incorrect)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_nb))

from sklearn.model_selection import cross_val_score

scores = cross_val_score(nb, X, y, cv=5)

print("Cross Validation Scores:", scores)
print("Average CV Score:", scores.mean())

